"""empty message

Revision ID: e530049d76cc
Revises: 
Create Date: 2020-04-06 10:42:02.509897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e530049d76cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codes', sa.String(length=60), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('expiration', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('delete_status', sa.String(length=5), nullable=False),
    sa.Column('activation_date', sa.DateTime(), nullable=True),
    sa.Column('regdate', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('app_id', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('delete_status', sa.String(length=15), nullable=False),
    sa.Column('regdate', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.Integer(), nullable=False),
    sa.Column('voice', sa.Text(), nullable=False),
    sa.Column('caption', sa.String(length=60), nullable=False),
    sa.Column('receiver', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('delete_status', sa.String(length=15), nullable=False),
    sa.Column('receive_delete_status', sa.String(length=15), nullable=False),
    sa.Column('read_date', sa.DateTime(), nullable=True),
    sa.Column('regdate', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suspects_reference', sa.Integer(), nullable=True),
    sa.Column('verification_message_id', sa.Integer(), nullable=True),
    sa.Column('verification_message_sender', sa.Integer(), nullable=True),
    sa.Column('opcodes', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=160), nullable=False),
    sa.Column('result', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('delete_status', sa.String(length=5), nullable=False),
    sa.Column('activation_date', sa.DateTime(), nullable=True),
    sa.Column('regdate', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suspects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution', sa.String(length=60), nullable=False),
    sa.Column('notification_phone', sa.String(length=15), nullable=False),
    sa.Column('notification_email', sa.String(length=60), nullable=False),
    sa.Column('names', sa.String(length=60), nullable=False),
    sa.Column('profile_id', sa.String(length=60), nullable=False),
    sa.Column('voices', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('delete_status', sa.String(length=15), nullable=False),
    sa.Column('last_message_id', sa.Integer(), nullable=True),
    sa.Column('last_trace_date', sa.DateTime(), nullable=True),
    sa.Column('regdate', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suspects')
    op.drop_table('operations')
    op.drop_table('messages')
    op.drop_table('contacts')
    op.drop_table('codes')
    # ### end Alembic commands ###
